const P=[
{id:1,title:'THE BINARY LOCK',label:'LEVEL 01 • DECODE',points:100,type:'input',answer:'Y',hint:'Convert 01011001 from binary to ASCII.',body:`<p>Decode the binary signal into one letter.</p><div class="codeblock">01011001</div><div class="answer"><input id="ans" maxlength="4" placeholder="Enter letter"><button class="btn primary" onclick="inputAnswer()">SUBMIT</button></div>`},
{id:2,title:'THE DATA ANOMALY',label:'LEVEL 02 • FIND THE OUTLIER',points:150,type:'choice',answer:2,hint:'Most values are around 100. Find the obvious outlier.',body:`<p>Which server value is abnormal?</p><div class="log">DATA HUB ........ 104 requests<br>MEMBER API ...... 97 requests<br>PARTNER PORTAL .. 847 requests<br>AUTH SERVICE .... 101 requests</div><div id="choices"></div>`},
{id:3,title:'THE BROKEN ALGORITHM',label:'LEVEL 03 • DEBUG',points:200,type:'choice',answer:1,hint:'The rule activates when requests exceed 1,000 per minute.',body:`<p>What triggered the automated action?</p><div class="log">IF requests_per_minute &gt; 1000<br>&nbsp;&nbsp;THEN download_latest_file()<br>&nbsp;&nbsp;AND notify_admin()<br>END</div><div id="choices"></div>`},
{id:4,title:'YEAR ONE MEMORY',label:'LEVEL 04 • FINAL CLUE',points:250,type:'choice',answer:0,hint:'Year One is complete. What comes next?',body:`<p>What phrase best represents the next chapter?</p><div id="choices"></div>`}
];
const C={2:['104 requests','101 requests','847 requests','97 requests'],3:['Manual download','Traffic threshold exceeded','Scheduled backup','Password change'],4:['YEAR TWO UNLOCKED','SYSTEM CLOSED','YEAR ONE REPEATED','NO FURTHER ACTION']};
let g={}; const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function startGame(){let n=$('name').value.trim();if(!n){$('name').focus();return}g={name:n,step:0,score:0,hints:0,end:Date.now()+900000,active:true};show('game');render();clock()}
function clock(){if(!g.active)return;let left=Math.max(0,g.end-Date.now()),s=Math.floor(left/1000),m=Math.floor(s/60);$('timer').textContent=String(m).padStart(2,'0')+':'+String(s%60).padStart(2,'0');$('timer').style.color=s<=60?'var(--bad)':'var(--text)';if(!left){finish(false);return}requestAnimationFrame(clock)}
function render(){let p=P[g.step];$('label').textContent=p.label;$('title').textContent=p.title;$('puzzleNo').textContent=`PUZZLE ${p.id} / 04`;$('body').innerHTML=p.body;$('bar').style.width=((g.step+1)*25)+'%';$('score').textContent=g.score;$('solved').textContent=g.step;$('hintBox').className='hint hidden';$('feedback').className='feedback hidden';$('hintBtn').disabled=false;if(p.type==='choice')C[p.id].forEach((t,i)=>{let b=document.createElement('button');b.className='choice';b.textContent=t;b.onclick=()=>answer(i===p.answer);$('choices').appendChild(b)})}
function inputAnswer(){answer($('ans').value.trim().toUpperCase()===P[g.step].answer)}
function answer(ok){let f=$('feedback');document.querySelectorAll('.choice').forEach(b=>b.disabled=true);if(ok){g.score+=P[g.step].points;f.className='feedback good';f.textContent='✓ ACCESS GRANTED  +'+P[g.step].points+' POINTS';$('score').textContent=g.score;setTimeout(()=>{g.step++;g.step<4?render():finish(true)},500)}else{g.score=Math.max(0,g.score-25);f.className='feedback bad';f.textContent='✕ SYSTEM ERROR  −25 POINTS. Try again.';$('score').textContent=g.score;document.querySelectorAll('.choice').forEach(b=>b.disabled=false)}}
function hint(){if(!$('hintBox').classList.contains('hidden'))return;g.score=Math.max(0,g.score-50);g.hints++;$('score').textContent=g.score;$('hintBox').textContent='HINT: '+P[g.step].hint;$('hintBox').className='hint';$('hintBtn').disabled=true}
function finish(solved){if(!g.active)return;g.active=false;if(solved){let rem=Math.max(0,Math.floor((g.end-Date.now())/1000));g.score+=500+Math.min(500,rem);$('finalSmall').textContent='SYSTEM UNLOCKED';$('finalTitle').innerHTML='EXIT<br>FOUND';$('finalMsg').textContent=`Excellent work, ${g.name}. You solved the archive and unlocked the next chapter.`;$('code').textContent='Y2-360';$('explain').textContent='The final clue reveals: YEAR TWO UNLOCKED. A speed bonus has been added.`}else{$('finalSmall').textContent='SYSTEM LOCKED';$('finalTitle').innerHTML='TIME<br>UP';$('finalMsg').textContent=`The 15-minute window has expired, ${g.name}.`;$('code').textContent='LOCKED';$('explain').textContent='Restart the investigation and try again.'}$('finalScore').textContent=g.score.toLocaleString();save();show('final')}
function save(){let a=JSON.parse(localStorage.getItem('exitScores')||'[]');a.push({name:g.name,score:g.score,solved:g.step>=4});a.sort((x,y)=>y.score-x.score);localStorage.setItem('exitScores',JSON.stringify(a.slice(0,20)))}
function leaderboard(){let a=JSON.parse(localStorage.getItem('exitScores')||'[]');$('scores').innerHTML=a.length?a.map((x,i)=>`<div class="row"><div class="rank">#${i+1}</div><div><b>${esc(x.name)}</b><div class="muted">${x.solved?'EXIT FOUND':'TIME UP'}</div></div><div class="pts">${x.score.toLocaleString()}</div></div>`).join(''):'<p>No scores yet.</p>';show('board')}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
